-- Ejercicio 1
CREATE TABLE PROVINCIAS(
Codigo TINYINT,
Nombre VARCHAR(25) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(Codigo)
);
-- Insertar dos filas en la tabla provincias
INSERT INTO PROVINCIAS VALUES(10,'Murcia');
INSERT INTO PROVINCIAS VALUES(20,'Madrid');
-- Borrar Tabla
DROP TABLE PROVINCIAS;
-- Ejercicio 2
CREATE TABLE CIUDADES(
Nombre VARCHAR(25),
Habitantes INT SIGNED NOT NULL,
Pais VARCHAR(25) DEFAULT 'España'

);
-- Insertar --
INSERT INTO CIUDADES(nombre,habitantes)
VALUES ('Molina de segura',5500);
-- Selecionar la tabla
SELECT * FROM ciudades;
-- Ejercicio 3
CREATE TABLE BLOQUEPISOS(
CALLE VARCHAR(30) NOT NULL,
NUMERO TINYINT NOT NULL,
PISO TINYINT NOT NULL,
PUERTA char(1),
CODIGO_POSTAL TINYINT NOT NULL,
METROS TINYINT,
COMENTARIOS VARCHAR(60),
cod_zona TINYINT,
DNI VARCHAR(10),
CONSTRAINT PK_Clave PRIMARY KEY(CALLE,NUMERO,PISO,PUERTA,CODIGO_POSTAL)
);
-- Ejercicio 4
CREATE TABLE ANIMALES(
Id TINYINT auto_increment,
Nombre VARCHAR(30) UNIQUE,
CONSTRAINT PK_ID PRIMARY KEY(Id)
);

INSERT INTO animales (nombre) VALUES ("GATO");
INSERT INTO animales (nombre) VALUES ("PERRO");
-- Ejercicio 5
CREATE TABLE EDADES(
NOMBRE VARCHAR(25) PRIMARY KEY,
EDAD TINYINT,
COD_PROVINCIA TINYINT,
CONSTRAINT FK_PROVINCIA FOREIGN KEY(COD_PROVINCIA) references provincias(Codigo)

);
-- Ejercicio 6
CREATE TABLE CONDICIONES(
DNI VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
EDAD TINYINT,
CURSO TINYINT NOT NULL,
CONSTRAINT comprobar_edad check (edad between 10 and 20 )

);


